version: '3.8'

services :

  web:
<<<<<<< HEAD
    image: caiocoutinhonvt/jungle-devs
    container_name: web
=======
    build: .
>>>>>>> 552d4c350106bbe0a27c4ced3ebc402d6e53c48b
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:10-alpine
    container_name: db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db

    volumes:
      - postgres:/var/lib/postgresql/data/

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    depends_on: 
      - db
    ports:
      - 8080:8080

volumes:
  postgres: