# Generated by Django 4.0.4 on 2022-05-19 20:47

from django.db import migrations, models
import jungledevs.models


class Migration(migrations.Migration):

    dependencies = [
        ('jungledevs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=jungledevs.models.upload_image_book),
        ),
    ]
