# Generated by Django 4.0.4 on 2022-05-19 21:04

from django.db import migrations, models
import jungledevs.models


class Migration(migrations.Migration):

    dependencies = [
        ('jungledevs', '0002_articles_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='image',
        ),
        migrations.AddField(
            model_name='author',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=jungledevs.models.upload_image_book),
        ),
    ]
