# Generated by Django 4.0.4 on 2022-05-21 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jungledevs', '0003_remove_articles_image_author_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='body',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='articles',
            name='first_paragraph',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
