# Generated by Django 4.0.4 on 2022-05-21 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jungledevs', '0004_articles_body_articles_first_paragraph'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articles',
            old_name='first_paragraph',
            new_name='firstParagraph',
        ),
    ]
